<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/Pagecreator.UI.Utils.js'))
        ->prependFile($this->basePath('js/Pagecreator.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</head>
<body>
<div id="main">
    <!-- header -->
    <div id="header-container">
        <div id="header">
            <div id="logo">
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                    &nbsp;Home
                </a>
            </div>
            <!-- end #logo -->
            <div class="clearfix"></div>
        </div>
    </div><!-- end #header-container -->

    <div class="clearfix"></div>
    <!-- content -->
    <div id="main-container" class="clearfix">
        <div id="content-wrapper">
            <?php echo $this->content; ?>
        </div>
    </div>

    <!-- footer -->
    <footer>
        <span>&copy; <?php echo date('Y') ?> by TB <?php echo $this->translate('All rights reserved.') ?></span>
    </footer>
    <!-- /container -->
    <?php echo $this->inlineScript() ?>
</div>

<script>
    $("#main-container").css("top", $("#header-container").outerHeight() + $("#headerbar").outerHeight());
</script>
</body>
</html>
