<?php if ($this->flashMessenger()->hasSuccessMessages()) : ?>
    <div class="clearfix alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message) ?>
        <strong>Erfolg</strong><br/>
        <?=$message ?>
    </div>
<?php endif; ?>
<?php if ($this->flashMessenger()->hasErrorMessages()) : ?>
    <div class="clearfix alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php foreach ($this->flashMessenger()->getErrorMessages() as $message) ?>
        <strong>Error</strong><br/>
        <?=$message ?>
    </div>
<?php endif; ?>

<div class="headerbar-wrapper" >
    <div class="headerbar">
        <div class="pull-right">
            <a class="btn btn-success" href="/pagecreator/add">
                <span class="glyphicon glyphicon-plus fa-1x" aria-hidden="true"></span> Website erstellen</a>
        </div>
    </div>
    <!-- end .headerbar -->
    <div style="display: block; width: 100%; height: 47px; float: none;"></div>
</div>

Now this is a story over Belair